;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
;   DON'T REPLACE THESE OPTIONS
;
;   In your custom context menu options file, fill out whatever info you want.
;   The Length variable needs to be set to the number of entries in the menu.
;   
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


[Variables]
Width=100
Length=1
MouseOverColour = 0,0,200,50
SeparatorColour = 0,0,0,60
ShadowColour = 0,0,0,100
BackgroundColour = 235,235,235,255
BorderColour = 0,0,0,100
FontColour = 0,0,0,255


; Separators
Separator1 = 0
Separator2 = 0
Separator3 = 0
Separator4 = 0
Separator5 = 0
Separator6 = 0
Separator7 = 0
Separator8 = 0
Separator9 = 0
Separator10 = 0
Separator11 = 0
Separator12 = 0
Separator13 = 0
Separator14 = 0
Separator15 = 0

; Icons
Icon1 =
Icon2 =
Icon3 =
Icon4 =
Icon5 =
Icon6 =
Icon7 =
Icon8 =
Icon9 =
Icon10 =
Icon11 =
Icon12 =
Icon13 =
Icon14 =
Icon15 =

; Texts
Text1 =
Text2 =
Text3 =
Text4 =
Text5 =
Text6 =
Text7 =
Text8 =
Text9 =
Text10 =
Text11 =
Text12 =
Text13 =
Text14 =
Text15 =

; Bangs
Bang1 =
Bang2 =
Bang3 =
Bang4 =
Bang5 =
Bang6 =
Bang7 =
Bang8 =
Bang9 =
Bang10 =
Bang11 =
Bang12 =
Bang13 =
Bang14 =
Bang15 =

